### ISSUE TITLE
Error: Invalid header flag bits, must be 0x0 for puback packet

### ISSUE THREAD

**Issue by NAUGHTY-BRAND** [JustKemForFun/Meta-Horizon#5]
~/WhisperedBossyTelecommunications$ node index
[ META-HZI ] ➣ Khởi Động Tiến Trình Đăng Nhập !
[ META-HZI ] ➣ Chưa Sẵn Sàng Để Giải Hóa AppState !
[ META-HZI ] ➣ Đăng Nhập Tại ID: 100046189680705
[ META-HZI ] ➣ Vùng Của Tài Khoản Là: ODN
[ META-HZI ] ➣ Phiên Bản Đang Dùng Hiện Tại Là: 1.4.1 !
[ META-HZI ] ➣ Tổng Thời Gian Bạn Sử Dụng: 00 Hours 00 Minutes 00 Seconds
[ META-HZI ] ➣ Cảm Ơn Đã Sử Dụng FCA Của Meta Horizon !
[ META-HZI ] ➣ Mã Hoá AppState Thành Công !
[ META-HZI ] ➣ Kết Thúc Với: 4s !
[ META-HZI ] ➣ Bạn Đang Sài Phiên Bản: Premium Access
ERR! listenMqtt Error: Invalid header flag bits, must be 0x0 for puback packet
ERR! listenMqtt     at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30)
ERR! listenMqtt     at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45)
ERR! listenMqtt     at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20)
ERR! listenMqtt     at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
ERR! listenMqtt     at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
ERR! listenMqtt     at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
ERR! listenMqtt     at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20)
ERR! listenMqtt     at Duplexify.emit (node:events:519:28)
ERR! listenMqtt     at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12)
ERR! listenMqtt     at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11)
ERR! listenMqtt     at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10)
ERR! listenMqtt     at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12)
ERR! listenMqtt     at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14)
ERR! listenMqtt     at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9)
ERR! listenMqtt     at WebSocket.emit (node:events:519:28)
ERR! listenMqtt     at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20)
ERR! listenMqtt  Error: Invalid header flag bits, must be 0x0 for puback packet
ERR! listenMqtt     at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30)
ERR! listenMqtt     at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45)
ERR! listenMqtt     at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20)
ERR! listenMqtt     at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
ERR! listenMqtt     at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
ERR! listenMqtt     at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
ERR! listenMqtt     at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20)
ERR! listenMqtt     at Duplexify.emit (node:events:519:28)
ERR! listenMqtt     at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12)
ERR! listenMqtt     at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11)
ERR! listenMqtt     at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10)
ERR! listenMqtt     at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12)
ERR! listenMqtt     at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14)
ERR! listenMqtt     at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9)
ERR! listenMqtt     at WebSocket.emit (node:events:519:28)
ERR! listenMqtt     at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20)

```js
const fs = require("fs");
const login = require("./meta-horizonnn");

login({appState: JSON.parse(fs.readFileSync('a.json', 'utf8'))}, (err, api) => {
    if(err) return console.error(err);
    fs.writeFileSync('appstate.json', JSON.stringify(api.getAppState(), null,'\t'));
    api.listenMqtt((err, message) => {
          //  api.sendMessage(message.body, message.threadID);
        });
    });```

**Comment by JustKemForFun** [comment]
let me see

**Comment by NAUGHTY-BRAND** [comment]
> let me see

ok

**Comment by JustKemForFun** [comment]
> ~/WhisperedBossyTelecommunications$ node index [ META-HZI ] ➣ Khởi Động Tiến Trình Đăng Nhập ! [ META-HZI ] ➣ Chưa Sẵn Sàng Để Giải Hóa AppState ! [ META-HZI ] ➣ Đăng Nhập Tại ID: 100046189680705 [ META-HZI ] ➣ Vùng Của Tài Khoản Là: ODN [ META-HZI ] ➣ Phiên Bản Đang Dùng Hiện Tại Là: 1.4.1 ! [ META-HZI ] ➣ Tổng Thời Gian Bạn Sử Dụng: 00 Hours 00 Minutes 00 Seconds [ META-HZI ] ➣ Cảm Ơn Đã Sử Dụng FCA Của Meta Horizon ! [ META-HZI ] ➣ Mã Hoá AppState Thành Công ! [ META-HZI ] ➣ Kết Thúc Với: 4s ! [ META-HZI ] ➣ Bạn Đang Sài Phiên Bản: Premium Access ERR! listenMqtt Error: Invalid header flag bits, must be 0x0 for puback packet ERR! listenMqtt at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30) ERR! listenMqtt at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45) ERR! listenMqtt at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20) ERR! listenMqtt at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) ERR! listenMqtt at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) ERR! listenMqtt at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10) ERR! listenMqtt at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20) ERR! listenMqtt at Duplexify.emit (node:events:519:28) ERR! listenMqtt at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12) ERR! listenMqtt at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11) ERR! listenMqtt at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10) ERR! listenMqtt at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12) ERR! listenMqtt at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14) ERR! listenMqtt at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9) ERR! listenMqtt at WebSocket.emit (node:events:519:28) ERR! listenMqtt at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20) ERR! listenMqtt Error: Invalid header flag bits, must be 0x0 for puback packet ERR! listenMqtt at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30) ERR! listenMqtt at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45) ERR! listenMqtt at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20) ERR! listenMqtt at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) ERR! listenMqtt at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) ERR! listenMqtt at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10) ERR! listenMqtt at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20) ERR! listenMqtt at Duplexify.emit (node:events:519:28) ERR! listenMqtt at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12) ERR! listenMqtt at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11) ERR! listenMqtt at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10) ERR! listenMqtt at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12) ERR! listenMqtt at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14) ERR! listenMqtt at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9) ERR! listenMqtt at WebSocket.emit (node:events:519:28) ERR! listenMqtt at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20)
> 
> ```js
> const fs = require("fs");
> const login = require("./meta-horizonnn");
> 
> login({appState: JSON.parse(fs.readFileSync('a.json', 'utf8'))}, (err, api) => {
>     if(err) return console.error(err);
>     fs.writeFileSync('appstate.json', JSON.stringify(api.getAppState(), null,'\t'));
>     api.listenMqtt((err, message) => {
>           //  api.sendMessage(message.body, message.threadID);
>         });
>     });```
> ```

can you use extension c3c get new appState test again?

**Comment by NAUGHTY-BRAND** [comment]
> > ~/WhisperedBossyTelecommunications$ node index [ META-HZI ] ➣ Khởi Động Tiến Trình Đăng Nhập ! [ META-HZI ] ➣ Chưa Sẵn Sàng Để Giải Hóa AppState ! [ META-HZI ] ➣ Đăng Nhập Tại ID: 100046189680705 [ META-HZI ] ➣ Vùng Của Tài Khoản Là: ODN [ META-HZI ] ➣ Phiên Bản Đang Dùng Hiện Tại Là: 1.4.1 ! [ META-HZI ] ➣ Tổng Thời Gian Bạn Sử Dụng: 00 Hours 00 Minutes 00 Seconds [ META-HZI ] ➣ Cảm Ơn Đã Sử Dụng FCA Của Meta Horizon ! [ META-HZI ] ➣ Mã Hoá AppState Thành Công ! [ META-HZI ] ➣ Kết Thúc Với: 4s ! [ META-HZI ] ➣ Bạn Đang Sài Phiên Bản: Premium Access ERR! listenMqtt Error: Invalid header flag bits, must be 0x0 for puback packet ERR! listenMqtt at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30) ERR! listenMqtt at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45) ERR! listenMqtt at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20) ERR! listenMqtt at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) ERR! listenMqtt at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) ERR! listenMqtt at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10) ERR! listenMqtt at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20) ERR! listenMqtt at Duplexify.emit (node:events:519:28) ERR! listenMqtt at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12) ERR! listenMqtt at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11) ERR! listenMqtt at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10) ERR! listenMqtt at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12) ERR! listenMqtt at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14) ERR! listenMqtt at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9) ERR! listenMqtt at WebSocket.emit (node:events:519:28) ERR! listenMqtt at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20) ERR! listenMqtt Error: Invalid header flag bits, must be 0x0 for puback packet ERR! listenMqtt at Parser._parseHeader (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:63:30) ERR! listenMqtt at Parser.parse (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt-packet/parser.js:43:45) ERR! listenMqtt at writable._write (/home/runner/WhisperedBossyTelecommunications/node_modules/mqtt/build/lib/client.js:251:20) ERR! listenMqtt at writeOrBuffer (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) ERR! listenMqtt at _write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:283:10) ERR! listenMqtt at Writable.write (/home/runner/WhisperedBossyTelecommunications/node_modules/readable-stream/lib/internal/streams/writable.js:286:10) ERR! listenMqtt at Duplexify.ondata (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:629:20) ERR! listenMqtt at Duplexify.emit (node:events:519:28) ERR! listenMqtt at addChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:279:12) ERR! listenMqtt at readableAddChunk (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:262:11) ERR! listenMqtt at Readable.push (/home/runner/WhisperedBossyTelecommunications/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:228:10) ERR! listenMqtt at WebSocket.onmessage (/home/runner/WhisperedBossyTelecommunications/meta-horizonnn/src/listenMqtt.js:74:12) ERR! listenMqtt at callListener (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:290:14) ERR! listenMqtt at WebSocket.onMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/event-target.js:209:9) ERR! listenMqtt at WebSocket.emit (node:events:519:28) ERR! listenMqtt at Receiver.receiverOnMessage (/home/runner/WhisperedBossyTelecommunications/node_modules/ws/lib/websocket.js:1220:20)
> > ```js
> > const fs = require("fs");
> > const login = require("./meta-horizonnn");
> > 
> > login({appState: JSON.parse(fs.readFileSync('a.json', 'utf8'))}, (err, api) => {
> >     if(err) return console.error(err);
> >     fs.writeFileSync('appstate.json', JSON.stringify(api.getAppState(), null,'\t'));
> >     api.listenMqtt((err, message) => {
> >           //  api.sendMessage(message.body, message.threadID);
> >         });
> >     });```
> > ```
> 
> can you use extension c3c get new appState test again?

sure let me do it bro

**Comment by JustKemForFun** [comment]
> sure let me do it bro

yes, if success, pls close issue

**Comment by NAUGHTY-BRAND** [comment]
> > sure let me do it bro
> 
> yes, if success, pls close issue

Ok bro
